name: CI test

# Trigger the workflow on push and cron
on:
  push:
  schedule:
  - cron:  '5 0 * * *'


jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        -
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'
        - name: Flake8 test
          run: |
            python3 -m venv myenv
            source myenv/bin/activate
            python -m pip install wheel
            python -m pip install flake8 pep8-naming
            python -m flake8 --show-source --statistics "$(basename $GITHUB_REPOSITORY)" test examples && echo "Flake8 found no errors."

  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
        - uses: actions/checkout@v2
        - name: Install miniforge
          shell: bash -l {0}
          run: |
            if [ "$(uname)" = "Darwin" ]; then
              brew install open-mpi
            else
              sudo apt-get -y install openmpi-bin libopenmpi-dev
            fi

            ./install.sh

        - name: Run tests
          shell: bash -l {0}
          run: |
            MINIFORGE_INSTALL_DIR=miniforge3
            source "$MINIFORGE_INSTALL_DIR/bin/activate" dgfem
            cd test
            python -m pytest --durations=10 --tb=native --junitxml=pytest.xml --doctest-modules -rxsw .

        - name: Run examples
          shell: bash -l {0}
          run: |
            MINIFORGE_INSTALL_DIR=miniforge3
            source "$MINIFORGE_INSTALL_DIR/bin/activate" dgfem
            examples/run_examples.sh ./examples
